# Generated by Django 4.1.4 on 2022-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Promotions",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
    ]
