# Generated by Django 4.1.4 on 2022-12-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_product_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="store.collection"
            ),
        ),
    ]
