# Generated by Django 4.1.4 on 2023-05-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=11,
            ),
        ),
    ]
