# Generated by Django 4.2.1 on 2023-05-21 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
