# Generated by Django 4.2.1 on 2023-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_customer_options_remove_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "can cancel order")]},
        ),
    ]
