# Generated by Django 4.2.2 on 2023-06-14 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can View history")],
            },
        ),
    ]
